### ISSUE TITLE
Error when delete unwanted users

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/Export-Import-Users#4]
I am using this to add users into phpbb3.1.10

I have entered the csv into store and it looks ok.

When I run the ext there is a preview where you can delete unwanted users.

When I chose delete I got an error & the error will not go away.

I have enabled & disabled the ext to no avail.

The error is this:

`General Error

SQL ERROR [ mysqli ]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR (username_clean = "" AND user_email = "")' at line 2 [1064]

SQL

SELECT user_id, username, user_password, user_email FROM phpbb_users WHERE user_id = OR (username_clean = "" AND user_email = "")

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/forumhulp/exportimportusers/acp/exportimportusers_module.php
LINE: 416
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: forumhulp\exportimportusers\acp\exportimportusers_module->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()`

**Comment by ForumHulp** [comment]
Thanks Daniel

 

I wil look at it next week.

Never so much work since 3.2 is out, what a mess

 

 

Greetz

 

 

Van: Daniel Mota [mailto:notifications@github.com] 
Verzonden: donderdag 19 januari 2017 16:13
Aan: ForumHulp/Export-Import-Users <Export-Import-Users@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ForumHulp/Export-Import-Users] Error when delete unwanted users (#4)

 

I am using this to add users into phpbb3.1.10

I have entered the csv into store and it looks ok.

When I run the ext there is a preview where you can delete unwanted users.

When I chose delete I got an error & the error will not go away.

I have enabled & disabled the ext to no avail.

The error is this:

`General Error

SQL ERROR [ mysqli ]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR (username_clean = "" AND user_email = "")' at line 2 [1064]

SQL

SELECT user_id, username, user_password, user_email FROM phpbb_users WHERE user_id = OR (username_clean = "" AND user_email = "")

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/forumhulp/exportimportusers/acp/exportimportusers_module.php
LINE: 416
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: forumhulp\exportimportusers\acp\exportimportusers_module->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()`

**Comment by Leinad4Mind** [comment]
Sure.

Btw search in Export-Import-Users/acp/exportimportusers_module.php "excists" and change to "exist" ;)

**Comment by ForumHulp** [comment]
Hi Daniel,

Can you send me you userfile you got this error with. 
Its a bit strange user_id and name or empty.

**Comment by Leinad4Mind** [comment]
It works on MySQL very good (at least for me, I just saw one little bug with that xml, but I could reenter on the extension again and continue deleting), but not on MariaDB on XAMPP (on a friend of mine, he can't enter again on the extension on acp).

Here you've an example:
[Uploading cadintoshmacusersoutputold.xml…]()

I guess it must be some sort of incompability with mariaDB maybe?

Cheers

**Comment by ForumHulp** [comment]
Aah ok that's the issue then
Your link redirects to this page

**Comment by Leinad4Mind** [comment]
Here it is: https://dl.dropboxusercontent.com/u/2651199/cadintoshmacusersoutputold.xml

Github doesnt accept xml and its not accepting the zip file.

**Comment by ForumHulp** [comment]
Thanks Daniel
But it's not a valid userlist.
Birthday and Pass aren't correct.

Pass should be like this $2y$10$8DkA7H8e1ZEg7ayJLjmlremt0uBcJhKbhEmlF2FKyMSgc5dOanRTy
and birthday like this 13- 1-1991

You can't import this

**Comment by Leinad4Mind** [comment]
I see, thanks for the report. If I encounter any bugs using a good .xml I'll tell.

Best regards

**Comment by Galixte** [comment]
I think it should be closed.
